dataset: mnist
lr: 1e-4                        # Learning rate
step_size: 150                  # Period of learning rate decay
lr_disc: 1e-4                   # Discriminator learning rate
step_size_disc: 150             # Period of discriminator learning rate decay
batch_size: 256                 # Mini-batch size
num_workers: 4                  # Number of cpu workers in pytorch dataloader
num_epochs: 200                 # Number of training epochs
fast_dev_run: false             # runs 1 batch of train, test and val
generator_idle_freq: 3          # Number of batches in which the generator is not updated

# Architecture
z_dim: 64                       # Latent variable dimension
architecture: cnn               # Which architecture to use (cnn or fc)

# Visualization
batches_to_viz: 5               # Number of batches to perform visualization
viz_num_per_batch: 10           # Number of images to visualize in a batch
viz_epoch_rate: 5               # Epoch frequency to save visualization (i.e. every 5 epochs)

hydra:
  run:
    # Output directory
    dir: ../output/ours_mnist_${now:%Y%m%d_%H%M%S}
