dataset: mnist_rotated
z_dim: 2            # Latent variable dimension
hidden_dim: 500     # Dimension of hidden layers
num_layers: 2       # Number of hidden layers
activation: tanh    # Activation function
dx_scale: 0.1       # Standard deviation of translation latent variables
theta_prior: 0.7854 # pi/4, standard deviation on rotation prior
lr: 1e-4            # Learning rate
batch_size: 128     # Mini-batch size
num_workers: 4      # Number of cpu workers in pytorch dataloader
num_epochs: 200     # Number of training epochs
fast_dev_run: false # runs 1 batch of train, test and val

hydra:
  run:
    # Output directory
    dir: ../output/${now:%Y%m%d_%H%M%S}
